In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Affichage des graphiques directement dans le notebook
%matplotlib inline

In [8]:
# Chargement des données brutes
df = pd.read_csv('../data/raw/pl_24-25_matches_clean.csv')

# Affichage des premières lignes
df.head()

,id,gameweek,dayofweek,date,start_time,home_team,home_xg,score,away_xg,away_team,attendance,venue,referee,notes,last_updated
0,1,1,Fri,2024-08-16,20:00,Manchester Utd,2.4,1–0,0.4,Fulham,NaN,Old Trafford,Robert Jones,NaN,2026-01-13 18:34:33.302
1,2,1,Sat,2024-08-17,12:30,Ipswich Town,0.5,0–2,2.6,Liverpool,NaN,Portman Road Stadium,Tim Robinson,NaN,2026-01-13 18:34:33.302
2,3,1,Sat,2024-08-17,15:00,Newcastle Utd,0.3,1–0,1.8,Southampton,NaN,St James' Park,Craig Pawson,NaN,2026-01-13 18:34:33.302
3,4,1,Sat,2024-08-17,15:00,Everton,0.5,0–3,1.4,Brighton,NaN,Goodison Park,Simon Hooper,NaN,2026-01-13 18:34:33.302
4,5,1,Sat,2024-08-17,15:00,Nott'ham Forest,1.3,1–1,1.2,Bournemouth,NaN,The City Ground,Michael Oliver,NaN,2026-01-13 18:34:33.302

In [11]:
# infos sur les colonnes, types et valeurs manquantes
df.info()

# Statistiques descriptives
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            380 non-null    int64
 1   gameweek      380 non-null    int64
 2   dayofweek     380 non-null    str
 3   date          380 non-null    str
 4   start_time    380 non-null    str
 5   home_team     380 non-null    str
 6   home_xg       380 non-null    float64
 7   score         380 non-null    str
 8   away_xg       380 non-null    float64
 9   away_team     380 non-null    str
 10  attendance    0 non-null      float64
 11  venue         380 non-null    str
 12  referee       380 non-null    str
 13  notes         0 non-null      float64
 14  last_updated  380 non-null    str
dtypes: float64(4), int64(2), str(9)
memory usage: 44.7 KB

               id    gameweek     home_xg     away_xg  attendance  notes
count  380.000000  380.000000  380.000000  380.000000         0.0    0.0
mean   190.500000   19.500000    1.492105    1.342895         NaN    NaN
std    109.840794   10.980313    0.821634    0.812194         NaN    NaN
min      1.000000    1.000000    0.100000    0.000000         NaN    NaN
25%     95.750000   10.000000    0.900000    0.800000         NaN    NaN
50%    190.500000   19.500000    1.300000    1.200000         NaN    NaN
75%    285.250000   29.000000    2.000000    1.700000         NaN    NaN
max    380.000000   38.000000    4.400000    5.600000         NaN    NaN

In [12]:
# Verifications des valeurs manquantes et doublons
print("Valeurs manquantes par colonne:\n", df.isna().sum())
print("Doublons:\n", df.duplicated().sum())

Valeurs manquantes par colonne:
 id                0
gameweek          0
dayofweek         0
date              0
start_time        0
home_team         0
home_xg           0
score             0
away_xg           0
away_team         0
attendance      380
venue             0
referee           0
notes           380
last_updated      0
dtype: int64
Doublons:
 0